#!/usr/bin/env bash

print_usage()
{
  echo "Usage: mrclope input output repulsion p maxIter number"
  echo "参数解释如下:"
  echo "  input		HDFS上的输入文件或者目录"
  echo "  output	HDFS上的输出目录"
  echo "  repulsion	排斥因子,符点型,一般大于1,值越大,生成聚类个数越多"
  echo "  p		排列参数,整型,会生成p!个map,值越大,准确率越高.建议设置不超过5"
  echo "  maxIter	最大迭代次数,整型,值越大,聚类越准确但花费时间越多"
  echo "  isNumber	数据记录的属性项是否需要编号,布尔型,用1|0表示"
}
# if no args specified, show usage
#[ $# = 0 ]
if [ $# != 6 ]; then 
  print_usage
  exit 1
fi

hadoop jar $MRClope_HOME/lib/MRClope.jar main.MRClope $1 $2 $3 $4 $5 $6
