#!/usr/bin/env bash

print_usage()
{
  echo "Usage: mrclope input output k"
  echo "参数解释如下:"
  echo "  input		输入文件或者目录,HDFS上的输入文件或者目录"
  echo "  output	输出目录,HDFS上的输出目录"
  echo "  k		聚类个数"
}
# if no args specified, show usage
#[ $# = 0 ]
if [ $# != 3 ]; then 
  print_usage
  exit 1
fi

hadoop jar $MRClope_HOME/lib/MRClope.jar main.View $1 $2 $3
